"""add history table

Revision ID: 55c20c5a327c
Revises: 4316161250ce
Create Date: 2026-05-14 21:05:50.529665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "55c20c5a327c"
down_revision: Union[str, Sequence[str], None] = "4316161250ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_history_created_at"), "history", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_history_user_id"), "history", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_tokens_exp"), "tokens", ["exp"], unique=False)
    op.create_index(
        op.f("ix_tokens_is_active"), "tokens", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_is_active"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_exp"), table_name="tokens")
    op.drop_index(op.f("ix_history_user_id"), table_name="history")
    op.drop_index(op.f("ix_history_created_at"), table_name="history")
    op.drop_table("history")
    # ### end Alembic commands ###
