"""In Track make artist_id optional

Revision ID: 1f8a4126e1da
Revises: 6b78eb34f750
Create Date: 2026-05-04 16:59:33.254342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1f8a4126e1da"
down_revision: Union[str, Sequence[str], None] = "6b78eb34f750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracks", "artist_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracks", "artist_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
