"""Change types of artist_id and album_id from str to int

Revision ID: 3055c8acff53
Revises: 1f8a4126e1da
Create Date: 2026-05-05 12:24:33.985774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3055c8acff53"
down_revision: Union[str, Sequence[str], None] = "1f8a4126e1da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
