"""Initial revision

Revision ID: 6b78eb34f750
Revises:
Create Date: 2026-05-04 07:50:54.632630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6b78eb34f750"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_key"),
    )
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=True)
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=True),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_key"),
    )
    op.create_index(
        op.f("ix_albums_artist_id"), "albums", ["artist_id"], unique=False
    )
    op.create_index(op.f("ix_albums_name"), "albums", ["name"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=True),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=True),
        sa.Column("genre", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_tracks_album_id"), "tracks", ["album_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracks_artist_id"), "tracks", ["artist_id"], unique=False
    )
    op.create_index(op.f("ix_tracks_title"), "tracks", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_artist_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_album_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_albums_name"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist_id"), table_name="albums")
    op.drop_table("albums")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
